# Generated by Django 5.2.1 on 2025-05-19 14:14

import django.utils.timezone
import vms_app.generate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='token',
            field=models.CharField(default=vms_app.generate.generate_short_token, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
