# Generated by Django 5.2.1 on 2025-05-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0002_user_must_change_password_alter_guest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
