# Generated by Django 5.2.1 on 2025-05-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0003_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestDevice',
        ),
    ]
