# Generated by Django 5.2.1 on 2025-06-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0004_delete_guestdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
