# Generated by Django 5.2.1 on 2025-06-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0005_employeeprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
