# Generated by Django 5.2.1 on 2025-06-21 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='token_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
