# Generated by Django 5.2.1 on 2025-07-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0008_guest_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='qr_code',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='id_qr_code',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
