# Generated by Django 5.2.1 on 2025-07-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0009_alter_device_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='token_qr_code',
            field=models.URLField(blank=True),
        ),
    ]
