# Generated by Django 5.2.1 on 2025-07-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0010_alter_guest_token_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='device_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
