# Generated by Django 5.2.1 on 2025-07-15 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0011_alter_accesslog_device_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='device_serial',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='device',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.device'),
        ),
    ]
