# Generated by Django 5.2.1 on 2025-07-16 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0012_remove_accesslog_device_serial_accesslog_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 20, 22, 54, 618545, tzinfo=datetime.timezone.utc)),
        ),
    ]
