# Generated by Django 5.2.1 on 2025-07-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='owner_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.guest'),
        ),
    ]
