from django.urls import path, include
from rest_framework.routers import DefaultRouter  # DRF router to auto-generate URL patterns # type: ignore
from .views import EmployeeProfileViewSet, EmployeeViewSet, AdminEmployeesAPIView, SecurityEmployeesAPIView

# Initialize the router and register viewsets
router = DefaultRouter()

# Endpoint to manage user accounts with employee role
router.register(r"employees", EmployeeViewSet, basename="employee")

# Endpoint to manage employee profile details
router.register(r"employee-profiles", EmployeeProfileViewSet, basename="employee-profile")

urlpatterns = [
    # Include all routes generated by the router
    path("", include(router.urls)),

    # Custom admin-only endpoint to fetch all employees with extended data
    path('admin/employees/', AdminEmployeesAPIView.as_view(), name='admin-employees'),

    # Custom security-only endpoint to fetch all employees with extended data
    path('security/employees/', SecurityEmployeesAPIView.as_view(), name='security-employees'),
]
