# Generated by Django 5.2.1 on 2025-07-19 15:09

import datetime
import django.db.models.deletion
import vms_app.generate
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('purpose', models.TextField()),
                ('token', models.CharField(default=vms_app.generate.generate_short_token, editable=False, max_length=10, unique=True)),
                ('token_qr_code', models.URLField(blank=True)),
                ('token_expiry', models.DateTimeField(default=datetime.datetime(2025, 7, 20, 15, 9, 41, 413032, tzinfo=datetime.timezone.utc))),
                ('is_verified', models.BooleanField(default=False)),
                ('visit_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
            ],
        ),
    ]
