# Generated by Django 5.2.1 on 2025-07-19 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 15, 9, 59, 571728, tzinfo=datetime.timezone.utc)),
        ),
    ]
