# Generated by Django 5.2.1 on 2025-07-19 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_alter_guest_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 19, 17, 8, 574024, tzinfo=datetime.timezone.utc)),
        ),
    ]
