# Generated by Django 5.2.1 on 2025-07-21 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_alter_guest_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 16, 6, 8, 906313, tzinfo=datetime.timezone.utc)),
        ),
    ]
