# Generated by Django 5.2.1 on 2025-07-26 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_alter_guest_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 27, 12, 59, 49, 845156, tzinfo=datetime.timezone.utc)),
        ),
    ]
