# Generated by Django 5.2.1 on 2025-07-26 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_alter_guest_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 27, 13, 22, 28, 351035, tzinfo=datetime.timezone.utc)),
        ),
    ]
