# Generated by Django 5.2.8 on 2025-11-22 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_alter_guest_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 23, 16, 35, 51, 911369, tzinfo=datetime.timezone.utc)),
        ),
    ]
