from django.urls import path, include  # Django utilities for URL routing
from rest_framework.routers import DefaultRouter  # DRF router for automatic route handling # type: ignore
from .views import AdminDevicesAPIView, DeviceViewSet, SecurityDeviceViewSet  # Importing the required views

# Create a router and register the general device viewset (for CRUD operations)
router = DefaultRouter()
router.register(r"devices", DeviceViewSet, basename="device")

# Define URL patterns for this app
urlpatterns = [
    # Include all routes automatically generated by the router (e.g., /devices/, /devices/<id>/)
    path("", include(router.urls)),

    # Custom endpoint for admin to view all devices
    path('admin/devices/', AdminDevicesAPIView.as_view(), name='admin-devices'),

    # Custom endpoint for security to view a filtered list of devices
    path('security/devices/', SecurityDeviceViewSet.as_view({'get': 'list'}), name='security-devices'),
]
